apiVersion: apps/v1
kind: Deployment
metadata:
  name: aisdata-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aisdata-mongo
  template:
    metadata:
      labels:
        app: aisdata-mongo
    spec:
      volumes:
        - name: aisdata-mongo-storage
          persistentVolumeClaim:
            claimName: aisdata-mongo-storage-claim
      containers:
        - name: aisdata-mongo
          image: mongo
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
          volumeMounts:
            - name: aisdata-mongo-storage
              mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: aisdata-mongo-srv
spec:
  selector:
    app: aisdata-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aisdata-mongo-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 30Gi
