apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: rs-tracker-services.dev
      http:
        paths:
          - path: /api/aisdata/?(.*)
            backend:
              serviceName: aisdata-srv
              servicePort: 3000
